<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Swaps Report</title>
    <style>
        body {
            font-family: sans-serif;
            font-size: 12px;
        }
        h2 {
            text-align: center;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 11px;
        }
        th, td {
            border: 1px solid #444;
            padding: 6px;
            text-align: left;
        }
        th {
            background-color: #f0f0f0;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            text-align: center;
            color: #888;
        }
    </style>
</head>
<body>
    <h2>Redvers Finance – Battery Swaps Report</h2>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Rider</th>
                <th>Station</th>
                <th>Battery</th>
                <th>Diff (%)</th>
                <th>Amount (UGX)</th>
                <th>Payment Method</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($swaps as $i => $swap)
                <tr>
                    <td>{{ $i + 1 }}</td>
                    <td>{{ $swap->riderUser->name ?? 'Unknown' }}</td>
                    <td>{{ $swap->station->name ?? 'Unknown' }}</td>
                    <td>{{ $swap->battery->serial_number ?? 'N/A' }}</td>
                    <td>{{ $swap->percentage_difference ?? '-' }}</td>
                    <td>{{ number_format($swap->payable_amount ?? 0) }}</td>
                    <td>{{ ucfirst($swap->payment_method ?? 'N/A') }}</td>
                    <td>{{ \Carbon\Carbon::parse($swap->created_at)->format('d M Y') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Redvers Smart Battery Swap System • {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
